sciencecorp/synapse-python

- synapse/client/nodes/stream_in.py
Reverts removal of 'shape' field in stream-in node
> fix: replace 'shape' field in stream-in node

- synapse/simulator/nodes/electrical_broadband.py
- synapse/tests/test_ndtp.py
- synapse/tests/test_stream_out.py
- synapse/utils/ndtp.pyx
- synapse/utils/ndtp_types.py
- BE byte order
- Updated Electrical Broadband channel data packing -- it is tightly packed again
- Break up Electrical Broadband NDTP packets if they would exceed min MTU (1400ish)
> Refactor: switch all packed fields to big endian (network byte order)

- synapse/server/nodes/stream_out.py
- synapse/tests/test_stream_out.py
- synapse/utils/ndtp_types.py
Fixes
- NDTP msg sequence numbers in python not rolling over correctly (python can store seq_number > 2^16-1, but a value that big will overflow when packed into the NDTP header). With this change, the message pack() utils will roll the sequence number over as well
- Subsequent chunked ElectricalBroadband packets always had the same t0, which was only correct for the first chunk. Now new timestamps are calculated for the subsequent chunks based on t0, the sample rate and cumulative number of samples
> fix: fix sequence number rollover in StreamOut, ElectricalBroadband chunk packet timestamping

- .gitignore
- README.md
- synapse/cli/streaming.py
- synapse/client/nodes/stream_out.py
Increases the socket buffer size on the StreamOut Node. I've set it to 5MB currently since that is ~200ms worth of buffering at 200Mbit/sec which should be plenty for our current systems. The default OS UDP receive buffer size is normally much smaller than 5MB and needs to be adjusted manually by the user. 
Also sequence number counting to take into account overflow of the sequence number.
> Increase Stream Out recieve buffer size to decrease packet loss

- synapse/tests/test_ndtp.py
- synapse/tests/test_stream_out.py
- synapse/utils/ndtp.pyx
bump NDTPPayloadSpiketrain_BIT_WIDTH to 4 in line with ndtp.h value for similar named struct in libndtp repo. [libndtp repo reference here](https://github.com/sciencecorp/libndtp/blob/5e0f16dc4f1ae96f409f4acc627b39588f61223b/include/science/libndtp/ndtp.h#L124).
> fix: increase spiketrain payload bit width to 4

- synapse/cli/discover.py
- synapse/server/autodiscovery.py
- synapse/server/entrypoint.py
- synapse/utils/discover.py
This changes the autodiscovery system to a broadcast-beacon based protocol rather than a multicast based protocol. The aim of this was to improve reliability on networks that dont support multicast, and hopefully improve the reliability of device discovery.
Switching to a UDP-broadcast based system comes with the caveat that it may place unnecessary strain on a network if a large number of SciFis are connected. However for current use-cases broadcast shouldn't be causing meaningful network congestion. 
Tested using a corresponding server implementation [here](https://github.com/sciencecorp/headstage/pull/145)
I tested that the autodiscovery remains working when:
- autodiscovery starts before the device is connected to a network
- the device disconnects from a network while autodiscovery …
> Initial impl of beacon-based autodiscovery

- synapse/cli/rpc.py
- synapse/client/config.py
- synapse/client/nodes/spectral_filter.py
- synapse/client/nodes/spike_detect.py
The dangling `from_proto()` call in the spike detect and spectral filter node causes configs to be improperly read. They seem to have missed the switchover to exclusively using `_from_proto()`.
> Fix bug in reading spike detect and filter node from proto.

- synapse/cli/rpc.py
- synapse/client/device.py
Ive built out the logging for start/stop/configure calls so we get the same pretty printing as with the stop command.
> More consistent logging of rpc errors

- synapse/server/nodes/stream_out.py
- synapse/simulator/nodes/broadband_source.py
- synapse/simulator/nodes/spike_source.py
- synapse/utils/ndtp_types.py
BREAKING CHANGE: switch generated timestamps from us to ns
---
On the topic, `ElectricalBroadbandData` should probably become `BroadbandData`; and we might as well add units to all fields where applicable, if we're going to have breaking changes
> feat: switch timestamps (sim BroadbandSource) to nanoseconds

- requirements.txt
- synapse/cli/streaming.py
We didn't sync our pip setup.py and our requirements, resulting in diverging protobuf dependencies. 
This manifested as:
```
Traceback (most recent call last):
File "/home/gilbert/workspace/wip/science-python-temp/.venv/bin/synapsectl", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/gilbert/workspace/wip/science-python-temp/.venv/lib/python3.12/site-packages/synapse/cli/__main__.py", line 42, in main
args.func(args)
File "/home/gilbert/workspace/wip/science-python-temp/.venv/lib/python3.12/site-packages/synapse/cli/streaming.py", line 210, in read
runtime_config_json = MessageToJson(
^^^^^^^^^^^^^^
TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'
```
* Tested locally, could stream
> fix: bump protobuf usage to latest

- synapse/cli/streaming.py
We were accidentally calling configure() a second time after configure() was called the first time.
> Remove duplicated configuration in streaming.py

- synapse/cli/offline_plot.py
Some fields in a channel were omitted (since '0' is the default (u)int value, it is omitted during serialization -- so a missing 'id' field is equivalent to id==0)
I also encountered overflows on the final_data parsing
> fix: fix issue with parsing configs with no electrode `id`, `electrode_id`

- README.md
- synapse/cli/__main__.py
- synapse/cli/discover.py
- synapse/cli/streaming.py
- synapse/client/node.py
- synapse/client/nodes/stream_out.py
- synapse/examples/stream_out.py
- synapse/server/entrypoint.py
- synapse/server/nodes/stream_out.py
- synapse/server/rpc.py
- synapse/tests/util/test_packet_monitor.py
- synapse/utils/packet_monitor.py
- test_config.json
In preparation for switching to UDP unicast, we have updated the StreamOut configuration to support udp unicast
* Updates synapse api
* Modularizes packet loss/bitrate calculation in streaming
* Updates stream out to use Udp unicast
StreamOut configurations can just be defined like this (with an empty configuration for stream_out)
```
{
"type": "kStreamOut",
"id": 1,
"stream_out": {
}
},
```
The client will automatically fill with the clients IP and a default streaming port. You can also set a different port yourself, like this:
```
{
"type": "kStreamOut",
"id": 1,
"stream_out": {
"udp_unicast": {
"destination_port": 12345
}
}
},
```
Specific IP addresses will not work, unless it is your own. In most cases, just let the client figure out the correct IP/Port to use.
* Tested streaming from …
> feature: upgrade to use udp unicast

- synapse/cli/rpc.py
```
Traceback (most recent call last):
File "/Users/antoniae/projects/science/synapse/.venv/bin/synapsectl", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/antoniae/projects/science/synapse/synapse-python/synapse/cli/__main__.py", line 43, in main
args.func(args)
File "/Users/antoniae/projects/science/synapse/synapse-python/synapse/cli/rpc.py", line 113, in query
f"impedance_measurements_{time.strftime('%Y%m%d-%H%M%S')}.csv", "w"
^^^^
```
> fix: fix missing import needed for impedance results saving

- synapse/cli/streaming.py
- synapse/client/nodes/stream_out.py
Closes #92 by adding a timeout to socket recv operations for the StreamOut node. When the socket stops sending data the CLI will show an error that it failed to get data from the socket. Tested with SciFi.
> Fix streaming getting stuck with no socket timeout (#92)

- synapse/cli/offline_plot.py
The DiskWriter node now outputs data in a .dat format which includes a header for mapping channel indexes to channel IDs. This updates offline plotting to support those files.
> Support new channel mapping header

- README.md
- synapse/cli/__main__.py
- synapse/cli/files.py
- synapse/cli/rpc.py
- synapse/cli/streaming.py
- synapse/utils/discover.py
Users have requested that it would be nice to just search by the device name, not only the IP. This removes the uri positional arguments for the CLI and adds the option of --uri with either <ip> or <device name>
```
python3 synapse/cli/__main__.py --uri <device_name/device_ip> info
```
> [feature] Allow users to search by name or ip

- synapse/utils/time_sync.py
* feat: add `get_last_sync_time_ns` to TimeSyncClient
* fix: fix issue where TimeSyncClient would send too many packets (send next packet upon previous receipt of previous packet's response, or timeout waiting for response)
To test
```
source .venv/bin/activate
pip install -e .
python synapse/utils/time_sync.py --host <your time server IP / scifi server IP>
```
`starling` and `fluffy-eldritch-hummingbird` support the time server and you may use their IPs.
> feat: add `get_last_sync_time_ns` to TimeSyncClient

- synapse/cli/__main__.py
- synapse/client/device.py
If we pass in a None uri, then we get an error. This catches it and explains the issue, while also printing the help.
- tested without -u flag
> feat: Fix issue where uri is forgotten

- synapse/client/device.py
Fixes error on some client Device methods on python v ~= 3.10
``` 
~/p/s/sy/synapse-python feature/doub…plot-parsing ❯ synapsectl plot --dir 2025-04-25-broadband-filter-hg-anterior
Traceback (most recent call last):
File "/Users/antoniae/projects/science/synapse/synapse-python/.venv_debug/bin/synapsectl", line 5, in <module>
from synapse.cli import main
File "/Users/antoniae/projects/science/synapse/synapse-python/synapse/__init__.py", line 1, in <module>
from synapse.client import *
File "/Users/antoniae/projects/science/synapse/synapse-python/synapse/client/__init__.py", line 3, in <module>
from synapse.client.device import Device
File "/Users/antoniae/projects/science/synapse/synapse-python/synapse/client/device.py", line 22, in <module>
class Device(object):
File …
```
> fix: fix issue with LogLevel type annotation on certain client device methods

- synapse/cli/__main__.py
- synapse/cli/build.py
- synapse/cli/deploy.py
- synapse/cli/rpc.py
- synapse/server/nodes/base.py
- synapse/server/rpc.py
this PR looks huge but is mostly copying code directly out of deploy.py into build.py.
the following should now work:
```
synapsectl build /path/to/app
synapsectl build /path/to/app --skip-build  # this will skip compiling in docker and just package a deb
```
the deploy command remains unchanged if you call it the same way:
```
synapsectl -u <scifi_name> deploy /path/to/app  # builds, packages, and deploys as before
```
but you can also now bypass building and packaging by passing a package instead of a path:
```
synapsectl -u <scifi_name> deploy --package /path/to/your/deb
```
> split out a build command from the synapsectl deploy command

- synapse/cli/build.py
- synapse/cli/deploy.py
Removes the ssh logins for deploying an app, as that is all handled by the device now. 
Note: We are still waiting on the device PR, so you will need to wait to update your device to test this. 
- Tested deploy with and without --package, worked
> feature: Upload and update package api

- .github/workflows/release.yml
- setup.py
Missed hdf5 in the imports for setup, increased wait time.
> hotfix: add hdf5

- synapse/cli/offline_hdf5_plotter.py
- synapse/cli/offline_plot.py
- synapse/cli/streaming.py
- synapse/cli/synapse_plotter.py
- synapse/client/taps.py
- improves errors during offline plot
- improves data recording performance during read
- adds --duration back in to read
- stops device on read close
- centers plot for single channel
- down sample factor is configurable
> feature: improvements from testing

- setup.py
- synapse/cli/offline_hdf5_plotter.py
- synapse/cli/streaming.py
Supports the updated broadband frame data type and hdf5 format. Also detects gaps in plotting data.
> Feature: Support updated hdf5 layout

- synapse/cli/device_info_display.py
- synapse/cli/offline_hdf5_plotter.py
- synapse/cli/synapse_plotter.py
* Adds ability to toggle DC offset view in live plotter
* Displays the connected peripheral to a broadband source
* Allows for better viewing of live gpio toggling.
> feature: make live plotting better for gpio

- README.md
updated readme with a small number of things
1. added "build" to the list of commands 
2. added description for it
3. added a point to check out synapse-example-app to know more about deployment and build
> Update README.md with improvements

- synapse/cli/build.py
Adds the --clean flag to the build command, which will force a clean build of the app. Users have requested this to ensure that the newest build is being used.
> feature: Add ability to clean on build

- synapse/cli/__main__.py
- synapse/cli/settings.py
- synapse/client/__init__.py
- synapse/client/device.py
- synapse/client/settings.py
We would like the ability to set device settings, which are options that can be set for a device that don't change between configuration runs.
> feature: demonstrate settings api

- synapse/cli/device_info_display.py
Adds the optical stimulation display information to the info command.
> feature: display optical stim in info

- synapse/examples/tap_example.py
- synapse/server/nodes/base.py
- synapse/server/rpc.py
- synapse/simulator/nodes/broadband_source.py
This is a change for #125. I wasn't sure if there's another simulated/virtual SciFi device that I should write the example against so I went ahead and updated the simulated broadband source in this repo to stream data over tap API. Also migrates legacy ndtp type to BroadbandFrame.
```
synapse-sim --iface-ip 127.0.0.1
```
1. script
```
python synapse/examples/tap_example.py
```
2. CLI
```
➜  synapsectl discover
⠼ Discovering Synapse devices... Found 1 so far (⌘C to stop)
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name                                       ┃                            Host ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ vague-strange-oryx                         │                   192.168.29.38 │ …
```
> Feature: Tap API in simulated broadband source
